/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.egcc.mateapp.view;

import javax.swing.JInternalFrame;

/**
 *
 * @author Alumno
 */
public class FormularioMDI extends javax.swing.JFrame {

    /**
     * Creates new form FormularioMDI
     */
    public FormularioMDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        menuMate = new javax.swing.JMenu();
        menuMateFactorial = new javax.swing.JMenuItem();
        menuMateMcdMcm = new javax.swing.JMenuItem();
        menuMateFibonacci = new javax.swing.JMenuItem();
        menuMatePrimo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        menuMate.setText("Matemáticas");

        menuMateFactorial.setText("Factorial");
        menuMateFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMateFactorialActionPerformed(evt);
            }
        });
        menuMate.add(menuMateFactorial);

        menuMateMcdMcm.setText("MCD y MCM");
        menuMateMcdMcm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMateMcdMcmActionPerformed(evt);
            }
        });
        menuMate.add(menuMateMcdMcm);

        menuMateFibonacci.setText("Fibonacci");
        menuMateFibonacci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMateFibonacciActionPerformed(evt);
            }
        });
        menuMate.add(menuMateFibonacci);

        menuMatePrimo.setText("Primo");
        menuMatePrimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMatePrimoActionPerformed(evt);
            }
        });
        menuMate.add(menuMatePrimo);

        menuBar.add(menuMate);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void menuMateFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMateFactorialActionPerformed
        /**
         * Para cargar la el panel interno JInternalFrame view; view = new
         * FactorialView(); desktopPane.add(view); view.setVisible(true);
         */
        cargarFormulario(FactorialView.class);
    }//GEN-LAST:event_menuMateFactorialActionPerformed

    private void menuMateMcdMcmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMateMcdMcmActionPerformed
        cargarFormulario(McdMcmView.class);
    }//GEN-LAST:event_menuMateMcdMcmActionPerformed

    private void menuMateFibonacciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMateFibonacciActionPerformed
        cargarFormulario(FibonacciView.class);
    }//GEN-LAST:event_menuMateFibonacciActionPerformed

    private void menuMatePrimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMatePrimoActionPerformed
        cargarFormulario(PrimoView.class);
    }//GEN-LAST:event_menuMatePrimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuMate;
    private javax.swing.JMenuItem menuMateFactorial;
    private javax.swing.JMenuItem menuMateFibonacci;
    private javax.swing.JMenuItem menuMateMcdMcm;
    private javax.swing.JMenuItem menuMatePrimo;
    // End of variables declaration//GEN-END:variables

    private void cargarFormulario(Class<?> aClass) {
        try {
            //Variable
            JInternalFrame view;

            //Buscar Instancia
            view = buscarInstancia(aClass);

            // Crear Instancia
            if (view == null) {
                view = (JInternalFrame) Class.forName(aClass.getName()).newInstance();
                desktopPane.add(view);
            }

            //Mostrar Formulario
            view.setVisible(true);
            view.setSelected(true);
        } catch (Exception e) {

        }
    }

    private JInternalFrame buscarInstancia(Class<?> aClass) {
        JInternalFrame view = null;
        for (JInternalFrame form : desktopPane.getAllFrames()) {
            if (aClass.isInstance(form)) {
                view = form;
                break;
            }
        }
        return view;
    }

}
