/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pe.crvm.aplicacionprueba.view;

import javax.swing.JInternalFrame;

/**
 *
 * @author Carlos
 */
public class RegistroMDI extends javax.swing.JFrame {

    /**
     * Creates new form RegistroPrimariaView
     */
    public RegistroMDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        MenuRegistros = new javax.swing.JMenu();
        MenuPrimaria = new javax.swing.JMenuItem();
        MenuSecundaria = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEMA DE MATRICULAS");
        desktopPane.add(jLabel1);
        jLabel1.setBounds(410, 40, 600, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/crvm/aplicacionprueba/Imagenes/Matricula.png"))); // NOI18N
        desktopPane.add(jLabel2);
        jLabel2.setBounds(1230, 160, 330, 370);

        menuBar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        fileMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/crvm/aplicacionprueba/Imagenes/Exit.png"))); // NOI18N
        fileMenu.setMnemonic('f');
        fileMenu.setText("Salir");
        fileMenu.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/crvm/aplicacionprueba/Imagenes/salir.png"))); // NOI18N
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        MenuRegistros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/crvm/aplicacionprueba/Imagenes/New.png"))); // NOI18N
        MenuRegistros.setText("Registros");
        MenuRegistros.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        MenuPrimaria.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        MenuPrimaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/crvm/aplicacionprueba/Imagenes/button_primaria.png"))); // NOI18N
        MenuPrimaria.setText("Nuevo Registro Primaria");
        MenuPrimaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPrimariaActionPerformed(evt);
            }
        });
        MenuRegistros.add(MenuPrimaria);

        MenuSecundaria.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        MenuSecundaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/crvm/aplicacionprueba/Imagenes/button_secundaria.png"))); // NOI18N
        MenuSecundaria.setText("Nuevo Registro Secundaria");
        MenuSecundaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSecundariaActionPerformed(evt);
            }
        });
        MenuRegistros.add(MenuSecundaria);

        menuBar.add(MenuRegistros);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/crvm/aplicacionprueba/Imagenes/Dial.png"))); // NOI18N
        jMenu1.setText("Acerca de");
        jMenu1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        jMenuItem1.setText("Integrantes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void MenuPrimariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPrimariaActionPerformed
        cargarFormulario(RegistroPrimariaView.class);
    }//GEN-LAST:event_MenuPrimariaActionPerformed

    private void MenuSecundariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSecundariaActionPerformed
        cargarFormulario(RegistroSecundariaView.class);
    }//GEN-LAST:event_MenuSecundariaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         cargarFormulario(Informacion.class);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuPrimaria;
    private javax.swing.JMenu MenuRegistros;
    private javax.swing.JMenuItem MenuSecundaria;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

    private void cargarFormulario(Class<?> aClass) { // <?> para cargar varios tipos de clase
         try {
            // Variable
             JInternalFrame view = null; 
            // Concepto Divide y venceras
             // Buscar instancia
            view =  buscarInstancia(aClass);
            // Crear instancia, solo si no lo encuentra
            if(view == null){
                // Creara la instancia
                view = (JInternalFrame) Class.forName(aClass.getName()).newInstance(); 
                desktopPane.add(view); // agregando al panel
            }
            // Mostrar Formulario
            view.setVisible(true);
            view.setSelected(true);
             
        } catch (Exception e) {
        }
    }

    private JInternalFrame buscarInstancia(Class<?> aClass) {
        JInternalFrame view = null;
        for(JInternalFrame form: desktopPane.getAllFrames()){ // desktopPane.getAllFrames(): arreglo de objetos
            if(aClass.isInstance(form)){ // aClass == form, 
                view=form;
                break;
            }
        }
        return view; // si nunca lo encuentra
    }
    

}
